version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.3.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Installing the Node Packages"
      - run: npm install
      - run: echo "build server"
      - run: npm run build:prod-server
      - run: echo "build client"
      - run: npm run build:prod-client
  test:
    docker: 
      - image: circleci/node:12.3.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: echo "Tesing the Application"
      - run: npm install
      - run: npm run test
workflows:
  version: 2.1
  test_lint_and_build:
    jobs:
      - test
      - build